### ISSUE TITLE
Add action to manually call docker build action

### ISSUE THREAD

**Issue by andreakreichgauer** [dot-base/.github#34]
### 🚀 Feature Description
We often ran into situations where we want to manually trigger a docker build action.
Thus we want to have an

### ✔ Goal
- [x] Add callable create Docker Build action https://github.com/dot-base/.github/commit/809a5937d8bc4b3a494d1f6019a70439a090e9eb
- [x] dot-base/icd-10-api#93
- [x] dot-base/hdp-adapter#66
- [x] dot-base/medical-dashboard#1393
- [x] dot-base/authentication-gateway#62
- [x] dot-base/patient-onboarding#31
- [x] dot-base/fhir-resources#476
- [x] dot-base/comm-server-adapter#44
- [x] dot-base/data-graph#96
- [x] dot-base/keycloak#80
- [x] dot-base/fhir-server#251
- [x] dot-base/error-handler#27
- [x] dot-base/file-storage-api#60
